language: go

go:
  - 1.9

env:
  - GOOS=darwin
  - GOOS=linux

script:
  - ./make_official.sh
  - ./spoon -help || true
  - ./spoon -version
  - ./spoon -generate > dummy.config.json
  - ./spoon -validate -config dummy.config.json
