language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

env:
  - GOOS=darwin
  - GOOS=linux

after_success:
  - ./spoon -help
  - ./spoon -version
  - ./spoon -generate > dummy.config.json
  - ./spoon -validate -config dummy.config.json
