
[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.17.11"

[[constraint]]
  name = "github.com/AstromechZA/go-statsd"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.03.2-ce"
