
[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.17.11"

[[constraint]]
  name = "github.com/AstromechZA/go-statsd"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "e11bf870a3170a1d2b1e177a0d7ccc66200bd643"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
